services:

  mysql: 
    image: mysql:latest
    container_name: serverMYSQL
    environment:
      - MYSQL_DATABASE=CR_Chat
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  
  postgres:
    image: postgres:latest
    container_name: serverPG
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=CR_Chat
    ports:
      - 5432:5432
    volumes:
      - ./postgreData:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False    
    ports:
      - 5050:80
    depends_on:
      - postgres
    
  web-datos:
    container_name: servidor-datos
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - postgres
      - mysql

volumes:
  postgres:
