services:

  servermysql:
    build:
      context: ./MySQLB
      dockerfile: Dockerfile
    container_name: servermysql
    environment:
      - MYSQL_DATABASE=CR_Chat
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./MySQLB/mysqlData:/var/lib/mysql
      - ./MySQLB/mysql-init:/docker-entrypoint-initdb.d
      - ./MySQLB/backup:/backup
      - ./MySQLB/logs:/var/log/mysqlbackup

  serverPG:
    image: cr_chat_postgresql
    container_name: serverPG
    environment:
      - POSTGRES_DB=CR_Chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    build:
      context: .
      dockerfile: ./Postgres/Dockerfile
    ports:
      - 5432:5432
    volumes:      
      - ./Postgres/postgreData:/var/lib/postgresql/data
      - ./Postgres/postgres-init:/docker-entrypoint-initdb.d
      - ./Postgres/backup:/backup
      - ./Postgres/logs:/var/log

  web-datos:
    container_name: servidor-datos
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - serverPG
      - servermysql
  
  presentacion:
    container_name: servidor-presentacion
    image: httpd:latest
    volumes:
      - ./presentacion:/usr/local/apache2/htdocs/
    ports:
      - 8001:80
    depends_on:
      - serverPG
      - servermysql

volumes:
  postgres:
