services:

  serverMYSQL: 
    image: mysql:latest
    container_name: serverMYSQL
    environment:
      - MYSQL_DATABASE=CR_Chat
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d

  serverPG:
    image: cr_chat_postgresql
    container_name: serverPG
    environment:
      - POSTGRES_DB=CR_Chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    build:
      context: .
      dockerfile: ./Postgres/Dockerfile
    ports:
      - 5432:5432
    volumes:      
      - ./Postgres/postgreData:/var/lib/postgresql/data
      - ./Postgres/postgres-init:/docker-entrypoint-initdb.d
      - ./Postgres/backup:/backup
      - ./Postgres/logs:/var/log

  
  web-datos:
    container_name: servidor-datos
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - serverPG
      - serverMYSQL

volumes:
  postgres:
