services:
  postgres:
    image: postgres:latest
    container_name: servidorPostgre
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=CR_Chat
    ports:
      - 5432:5432
    volumes:
      - ./postgreData:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False    
    ports:
      - 5050:80
    depends_on:
      - postgres
volumes:
  postgres:
